BiscuitDevelopment/SkyblockAddons

src/main/java/codes/biscuit/skyblockaddons/mixins/MixinGuiBeacon.java
src/main/java/codes/biscuit/skyblockaddons/mixins/MixinGuiContainer.java
src/main/resources/mixins.skyblockaddons.json

Previously, the wrong slots were locked. Here are results with changes:

Fixed locked slots w/ beacon inventories opened

---

src/main/java/codes/biscuit/skyblockaddons/utils/RomanNumeralParser.java

Oh boy, I didn't think of the case where numerals might be at the end of a word and "SWOR500" happened.
I fixed it in this now, and hope no other weird edge cases come up.

Fixed RomanNumeralsParser replacing numerals at the end of a word

---

src/main/java/codes/biscuit/skyblockaddons/utils/InventoryUtils.java

...and removed extra check for Quiver Arrow as it's no longer needed.
It basically just ignores the 8th slot entirely now

Fixed Item Pickup Log showing the Skyblock Menu

---

src/main/java/codes/biscuit/skyblockaddons/mixins/MixinGuiChest.java
src/main/java/codes/biscuit/skyblockaddons/utils/EnumUtils.java

Author: GoldenDusk
All Locations are now in the Location enum.
Plugin now hides players at all NPCs in Skyblock.
Merchant merged into SkyblockNPC. isMerchant moved to SkyblockNPC for merchant-only features.

Added all Locations and NPCs in Skyblock

---

src/main/java/codes/biscuit/skyblockaddons/listeners/RenderListener.java
src/main/java/codes/biscuit/skyblockaddons/mixins/MixinMinecraft.java
src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java
src/main/resources/mixins.skyblockaddons.json

Moved the old texture check to run only when the textures are reloaded rather than every frame (or twice per frame if you had both bars enabled). I also switched it to a hash comparison because it was about 2 ms faster in my testing and it's a bit cleaner.
closes #204

Fix the fps drop in the latest update.

---

src/main/java/codes/biscuit/skyblockaddons/utils/nifty/reflection/Reflection.java

Currently,  the Reflection cache keeps storing new ReflectionAccessor instances because it can't find any that are already stored, eventually running out of Memory.
Some of the HashMaps' Key-Types are Arrays, which doesn't work well with the way HashMap looks up its existing keys. `HashMap.containsKey(Object)` looks for the Key using `Object.equals(Object)`, which only compares references because equals() is not implemented in Array.
So instead iterate through HashMap and compare the Array's contents using `Arrays.equals`.

Prevent Endless HashMap Expansion

---

src/main/java/codes/biscuit/skyblockaddons/asm/hooks/EntityPlayerSPHook.java
src/main/java/codes/biscuit/skyblockaddons/listeners/PlayerListener.java

Add additional checks if Utils.isOnSkyblock returns false before/after server change

Fix drop prevention & slot locking failing during server change

---

src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java

This fixes a crash that happens whenever joining a singleplayer world.

Ensure that the player is in multiplayer before checking if they're on hypixel

---

src/main/java/codes/biscuit/skyblockaddons/utils/ItemDropChecker.java
src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java

This PR fixes:
- itemDropChecker opening the wrong file since it's named `lists/itemDropChecker.json` not `lists/itemDrop.json` 
- Discord Rich Presence module raising a NullPointerException and crashing the game since the default location was set to `null` instead of `Location.UNKNOWN`.
Feel free to correct me if I did something wrong or broke a thing.

Bug Fixes: itemDropChecker and Location

---

.github/workflows/build.yml

Fix the GitHub actions build. The issue was you didn't update the name of the build jar in the build file. I hardcoded the `-for-MC-1.8.9` since its the same in the build.gradle. Remember to update this next time you change the file name in build.gradle.

Fix github actions build.

---

src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java

It turns out that traditional Chinese uses a slightly different character in the Sidebar title, thus not enabling SkyblockAddons. 
This PR adds the traditional Chinese Skyblock name to the Set used for the check.

Add traditional Chinese support for the in-Skyblock check

---

src/main/java/codes/biscuit/skyblockaddons/core/DungeonPlayer.java
src/main/java/codes/biscuit/skyblockaddons/listeners/RenderListener.java

This PR contains a small fix to the dungeon features:
- ~(a23dd3d) Resolve the conflict between action bar and skill display~ (Can be resolved using **GUI Editor**)
- (29889d0) Don't show the critical sign to dead teammates

Dungeon Fix: Show critical sign to dead teammates

---

src/main/java/codes/biscuit/skyblockaddons/core/Feature.java

Two features`SHOW_ITEM_DUNGEON_FLOOR` and `SHOW_DUNGEON_MILESTONE` have the same ID 110
- Changed `SHOW_DUNGEON_MILESTONE` ID to 111

Important Fix: Two features have the same ID

---

src/main/java/codes/biscuit/skyblockaddons/core/DungeonPlayer.java
src/main/java/codes/biscuit/skyblockaddons/utils/TextUtils.java

In dungeons, any teammate who has '_' in their name is not included in the map.
That's because the character '_' is being filtered using `TextUtils#keepScoreboardCharacters`
This commit solves the problem by adding `_` to the pattern.
Sometimes, the prefix of the health color has a repeat (e.g. `§a§a`).
This causes the pattern to be broken.
This commit solves the problem by ignoring the repeated part.

Dungeon Fix: Doesn't detect teammates with symbols

---

src/main/java/codes/biscuit/skyblockaddons/features/powerorbs/PowerOrbManager.java

The `PowerOrbManager#hasPowerorbEntityChanged` was reading outside the array by using `EntityArmorStand#getCurrentArmor`.
This commit replaces it with `EntityArmorStand#getEquipmentInSlot`.

Fixes #375

---

src/main/java/codes/biscuit/skyblockaddons/asm/hooks/MinecraftHook.java
src/main/java/codes/biscuit/skyblockaddons/asm/hooks/PlayerControllerMPHook.java
src/main/java/codes/biscuit/skyblockaddons/features/cooldowns/CooldownManager.java
src/main/java/codes/biscuit/skyblockaddons/utils/InventoryUtils.java

This fixes Issue #438 by using .contains instead of .equals when matching axes, and replace the way it searches maps
[https://github.com/RobotHanzo/SkyblockAddons/suites/1393459570/artifacts/23067682](https://github.com/RobotHanzo/SkyblockAddons/suites/1393459570/artifacts/23067682)

[BUG FIX] Fixed axes with reforges not compatible with the cooldown features

---

src/main/java/codes/biscuit/skyblockaddons/asm/FontRendererTransformer.java
src/main/java/codes/biscuit/skyblockaddons/tweaker/SkyblockAddonsTransformer.java

Super lazy fix that should work on Patcher 1.5-1.7
Injects the chroma check into the Patcher renderStringAtPos method head instead of in the MC code (since Patcher transformer runs later + Patcher is switching to mixin), I didn't want a change in transformer order to break something
Removes other injection into Patcher's methods since SBA never updates so it's likely to break at some point

fix: inject chroma check into Patcher method head

---

src/main/java/codes/biscuit/skyblockaddons/asm/hooks/GuiNewChatHook.java
src/main/java/codes/biscuit/skyblockaddons/commands/SkyblockAddonsCommand.java
src/main/java/codes/biscuit/skyblockaddons/core/Feature.java
src/main/java/codes/biscuit/skyblockaddons/gui/EnchantmentSettingsGui.java
src/main/java/codes/biscuit/skyblockaddons/gui/IslandWarpGui.java
src/main/java/codes/biscuit/skyblockaddons/gui/LocationEditGui.java
src/main/java/codes/biscuit/skyblockaddons/gui/SettingsGui.java
src/main/java/codes/biscuit/skyblockaddons/gui/SkyblockAddonsGui.java
src/main/java/codes/biscuit/skyblockaddons/listeners/GuiScreenListener.java
src/main/java/codes/biscuit/skyblockaddons/listeners/PlayerListener.java
src/main/resources/lang/en_US.json

- Make dev mode setting persist across restarts
- Add dev mode toggle in general settings
- Separate show Skyblock item ID feature from dev mode
- Add a toggle for leather backpack opening sound
- Fix leather backpack opening sound conflicting with default Skyblock backpack opening sound
- Fix some warnings
- Simplify enabling/disabling features

Persist dev mode and fix backpack opening sound conflict

---

src/main/java/codes/biscuit/skyblockaddons/core/Feature.java
src/main/java/codes/biscuit/skyblockaddons/features/itemdrops/ItemDropChecker.java
src/main/java/codes/biscuit/skyblockaddons/listeners/PlayerListener.java
src/main/java/codes/biscuit/skyblockaddons/utils/EnumUtils.java
src/main/resources/lang/en_US.json
src/main/resources/lang/he_IL.json

Added a feature to display the profile type of a player in chat (ironman/bingo).
The feature requires the other player to be loaded for the icon to appear and there is a cache of recent players to keep the icon in case one goes so far they unload or they leave the lobby.
Also fixed a string typo in the item dropping feature that caused an unwanted string to print instead of a localized one,

Profile Type Icon In Chat + Typo Fix

---

src/main/java/codes/biscuit/skyblockaddons/features/dungeonmap/DungeonMapManager.java
src/main/java/codes/biscuit/skyblockaddons/gui/SettingsGui.java

Map zoom setting simply didn't function as it was normalized twice on saving.
I'm not sure why we need to save a normalized value as it would be much easier to denormalize it once when changing the slider and handling a normal value from that point. but I kept it that way to not mess with peoples existing settings.

Fixed issues with dungeon map zoom caused by impromper normalization.

---

src/main/java/codes/biscuit/skyblockaddons/listeners/PlayerListener.java
src/main/java/codes/biscuit/skyblockaddons/utils/TextUtils.java

Multiple transformation caused players mentioning themselves to allow the feature to transform the message body and break formatting.

Fix multiple username transformation
