src/main/resources/lang/fr_FR.json

French translation done.
Waiting to translate "Ember rod" because of no official translation

French translation (fr_FR.json)

---

src/main/resources/lang/fr_FR.json

Translate "off" & "minionCannotReach"
Fix punctuation

Update french translation

---

src/main/resources/lang/ru_RU.json

Added Russian language.

---

src/main/resources/lang/fr_fr.json

Fix #21, harmonization & new line translated

---

src/main/resources/lang/fr_fr.json

French sentences strikes again #33

Updated fr_fr.json for 1.1.2 update

---

src/main/resources/lang/es_mx.json

Updated es_mx.json

---

src/main/java/codes/biscuit/skyblockaddons/listeners/PlayerListener.java

Added how many times any item was placed in the anvil.

Added anvil usage

---

src/main/resources/lang/es_mx.json

Updated "es_mx.json"

---

src/main/java/codes/biscuit/skyblockaddons/mixins/MixinRenderManager.java
src/main/java/codes/biscuit/skyblockaddons/utils/EnumUtils.java

Now hides players at the baker, and fixed hiding players around lobby

Added baker to SkyblockNPC and fixed HIDE_PLAYERS_IN_LOBBY

---

src/main/java/codes/biscuit/skyblockaddons/mixins/MixinGuiChest.java

Added Keyboard repeating and update cursor for GuiTextField

---

src/main/java/codes/biscuit/skyblockaddons/utils/ConfigValues.java
src/main/java/codes/biscuit/skyblockaddons/utils/Language.java
src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java

- Fixed language loading
- Fixed URL to fetch featuredlink.txt

Mini fixes

---

src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java

Improved loop performance

---

src/main/java/codes/biscuit/skyblockaddons/utils/SkyblockDate.java

change EARLY_FALLL to EARLY_FALL

---

src/main/java/codes/biscuit/skyblockaddons/listeners/PlayerListener.java
src/main/java/codes/biscuit/skyblockaddons/mixins/MixinGuiChest.java
src/main/java/codes/biscuit/skyblockaddons/mixins/MixinGuiScreen.java
src/main/java/codes/biscuit/skyblockaddons/mixins/MixinItem.java
src/main/java/codes/biscuit/skyblockaddons/mixins/MixinPlayerControllerMP.java
src/main/java/codes/biscuit/skyblockaddons/utils/CooldownEntry.java
src/main/java/codes/biscuit/skyblockaddons/utils/CooldownManager.java
src/main/java/codes/biscuit/skyblockaddons/utils/InventoryUtils.java
src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java

Also moved cooldown management to `CooldownManager`

Added Maddox Batphone to the item cooldowns feature

---

src/main/java/codes/biscuit/skyblockaddons/utils/PersistentValues.java

Fixes #237 
Also cleaned up a bit the code, by properly closing the reader / writer on errors, and using it directly instead of loading the file to a string

Cleaned up PersistantValues and fixed a few issues with it #237

---

src/main/java/codes/biscuit/skyblockaddons/utils/Location.java
src/main/java/codes/biscuit/skyblockaddons/utils/npc/NPC.java

Add new update NPCs

---

README.md

When I tried to set up the development environment. I ran into issues and complications that took a long time (😓 ). Special thanks to @Berisan (😄 ) for helping me solve those issues.
So, This PR focuses on improving the **Contributors** section in [README](https://github.com/BiscuitDevelopment/SkyblockAddons/blob/development/README.md#for-contributors) by rewriting it.
The section is rewritten in a way that makes it simple and let the contributor focuses on contributing to the project. Instead of figuring out how to run and set up the project.
Also, This PR is part of #338.
Just visit the `README.md` in my fork by [clicking here](https://github.com/iHDeveloper/SkyblockAddons/blob/development/README.md#for-contributors).
**EDIT:** I'm sorry. I didn't understand the note in the …

[README] Rewrite the contributors section

---

src/main/java/codes/biscuit/skyblockaddons/listeners/PlayerListener.java

Improved Expertise enchant tooltip by addind next step before upgrade enchant & custom color

Improved Expertise enchant tooltip by addind next step before upgrade

---

src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java

The server brand was changed from Bungeecord (Hypixel) to Hypixel BungeeCord (1.0.0).

update Hypixel server brand for the Utils#isOnHypixel() check.

---

README.md

Previous alt texts were not related to the badges.

Fixed badge alt texts in the readme

---

src/main/java/codes/biscuit/skyblockaddons/commands/SkyblockAddonsCommand.java
src/main/java/codes/biscuit/skyblockaddons/config/PersistentValuesManager.java
src/main/java/codes/biscuit/skyblockaddons/core/Feature.java
src/main/java/codes/biscuit/skyblockaddons/core/Message.java
src/main/resources/lang/en_US.json

- Add reset zealot counter command
- Fix Fetchur persistent values crash
- Add docs to PersistentValuesManager

Add resetZealotCounter command, fix Fetchur persistent values crash

---

src/main/java/codes/biscuit/skyblockaddons/features/EntityOutlines/FeatureTrackerQuest.java
src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java
src/main/resources/lang/en_US.json

Made it a constant because it might be useful for other things later

Isolate short prefix from "messages.worldRenderedCooldownTime" string

---

src/main/java/codes/biscuit/skyblockaddons/gui/SettingsGui.java
src/main/java/codes/biscuit/skyblockaddons/gui/buttons/ButtonGuiScale.java
src/main/resources/lang/en_US.json

How did this ever get set to NaN... what?

Add error handling when GUI scale is infinite or NaN

---

src/main/java/codes/biscuit/skyblockaddons/SkyblockAddons.java

now macos players can copy nbt right away!

change dflt keybind of copynbt to LMENU for macos

---

src/main/java/codes/biscuit/skyblockaddons/core/Feature.java
src/main/java/codes/biscuit/skyblockaddons/core/Translations.java
src/main/java/codes/biscuit/skyblockaddons/gui/LocationEditGui.java
src/main/resources/lang/en_US.json

Also:
- Compacted translations error spam
- Added logging for ArabicShapingException in Translations

Add option to display feature names when hovering over features in GUI editor

---

src/main/java/codes/biscuit/skyblockaddons/SkyblockAddons.java
src/main/java/codes/biscuit/skyblockaddons/core/seacreatures/SeaCreatureManager.java
src/main/java/codes/biscuit/skyblockaddons/exceptions/DataLoadingException.java
src/main/java/codes/biscuit/skyblockaddons/misc/SkyblockKeyBinding.java
src/main/java/codes/biscuit/skyblockaddons/utils/DataUtils.java

- Add error screen when an essential file fails to load
- Reduce amount of copy-pasted stuff in DataUtils
- Load config and data files in pre-init instead of post
- Port sea creature data loading to DataUtils

Data file loading changes

---

src/main/java/codes/biscuit/skyblockaddons/features/dungeonmap/DungeonMapManager.java
src/main/java/codes/biscuit/skyblockaddons/features/dungeonmap/MapMarker.java
src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java

Closes #610 
not ready for merge until dungeon map is fixed

Fix dungeon features

---

src/main/resources/lang/en_US.json

This PR changes all verb forms in the commandUsage object from the infinitive to the present form as that makes more sense and feels more descriptive of what the commands do

chore(strings): change verb forms from infinitive to present

---

src/main/java/codes/biscuit/skyblockaddons/features/discordrpc/DiscordStatus.java

Fix DiscordRPC Stats float

---

src/main/java/codes/biscuit/skyblockaddons/asm/hooks/ModelEndermanHook.java
src/main/java/codes/biscuit/skyblockaddons/asm/hooks/RenderEndermanHook.java
src/main/java/codes/biscuit/skyblockaddons/core/Location.java

Added new end areas: Zealot Bruiser Hideout and Void Slate
Applied the change zealot color feature to the new end areas.

Added new end areas and applied the change zealot color feature to them

---

src/main/java/codes/biscuit/skyblockaddons/listeners/PlayerListener.java
src/main/java/codes/biscuit/skyblockaddons/utils/TextUtils.java
src/main/resources/META-INF/skyblockaddons_at.cfg

Fixing a few issues with the existing implementation.
including a modification to PR #680 which only worked on the player and not others.
and other formatting, colors, and spacing bugs.
As I dont use patcher, image preview compatibility needs to be tested.

Fixing issues with player symbols in chat
